<x-app-layout>
    <x-slot name="header"><div><h1 class="text-xl font-bold text-[#24313A]">Nova iniciativa</h1><p class="mt-1 text-sm text-[#667680]">Registre a demanda e defina como ela será conduzida</p></div></x-slot>
    <div class="mx-auto max-w-6xl space-y-5">
        <section class="sgp-page-intro"><p class="sgp-page-kicker">Porta de entrada</p><h2 class="mt-2 text-2xl font-bold">Comece com contexto, intenção e governança</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-white/80">A configuração inicial orienta aplicabilidade, jornada comercial, documentação e futura conversão em projeto.</p></section>
        @if ($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">Revise os campos destacados antes de continuar.</div>@endif
        <form method="post" action="{{ route('initiatives.store') }}" class="sgp-card p-5 sm:p-7">@csrf
            @error('initiative')<p class="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $message }}</p>@enderror
            <section class="sgp-form-section"><h2 class="sgp-section-heading">Identificação da iniciativa</h2><p class="sgp-section-description">Dê um nome claro e explique o problema, oportunidade ou necessidade.</p><div class="mt-5 grid gap-5 lg:grid-cols-2">
                <div><label class="sgp-field-label" for="title">Título <span class="text-[#C44B4B]">*</span></label><input class="sgp-input" id="title" name="title" value="{{ old('title') }}" maxlength="255" required autofocus placeholder="Ex.: Modernização do portal de atendimento"><p class="sgp-field-help">Use um título reconhecível pelas áreas envolvidas.</p><x-input-error :messages="$errors->get('title')" class="mt-2" /></div>
                <div><label class="sgp-field-label" for="origin">Origem <span class="text-[#C44B4B]">*</span></label><select class="sgp-input" id="origin" name="origin" required>@foreach ($origins as $value)<option value="{{ $value->value }}" @selected(old('origin') === $value->value)>{{ $value->label() }}</option>@endforeach</select><p class="sgp-field-help">A origem comercial habilita oportunidade e proposta.</p><x-input-error :messages="$errors->get('origin')" class="mt-2" /></div>
                <div class="lg:col-span-2"><label class="sgp-field-label" for="context">Contexto</label><textarea class="sgp-input min-h-32" id="context" name="context" maxlength="10000" placeholder="Descreva cenário atual, motivação, partes interessadas e resultado esperado.">{{ old('context') }}</textarea><x-input-error :messages="$errors->get('context')" class="mt-2" /></div>
            </div></section>
            <section class="sgp-form-section mt-7"><h2 class="sgp-section-heading">Configuração adaptativa</h2><p class="sgp-section-description">Defina as dimensões que orientarão o tratamento inicial.</p><div class="mt-5 grid gap-5 sm:grid-cols-2">
                @foreach (['execution_nature' => ['Natureza da execução', $executionNatures], 'financial_management_mode' => ['Gestão financeira', $financialModes], 'management_level' => ['Nível de gestão', $managementLevels], 'methodology' => ['Metodologia', $methodologies]] as $field => [$label, $values])
                    <div><label class="sgp-field-label" for="{{ $field }}">{{ $label }} <span class="text-[#C44B4B]">*</span></label><select class="sgp-input" id="{{ $field }}" name="{{ $field }}" required>@foreach ($values as $value)<option value="{{ $value->value }}" @selected(old($field) === $value->value)>{{ $value->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get($field)" class="mt-2" /></div>
                @endforeach
            </div></section>
            <section class="sgp-form-section mt-7"><h2 class="sgp-section-heading">Decisão inicial</h2><p class="sgp-section-description">Registre por que esta configuração é adequada neste momento.</p><div class="mt-5"><label class="sgp-field-label" for="justification">Justificativa <span class="text-[#C44B4B]">*</span></label><textarea class="sgp-input min-h-28" id="justification" name="justification" maxlength="10000" required placeholder="Explique os critérios adotados.">{{ old('justification') }}</textarea><x-input-error :messages="$errors->get('justification')" class="mt-2" /></div></section>
            <div class="mt-7 flex flex-col-reverse gap-3 border-t border-[#E8EDF0] pt-5 sm:flex-row sm:justify-end"><a class="sgp-button-secondary" href="{{ route('initiatives.index') }}">Cancelar</a><button class="sgp-button-primary sm:w-auto" type="submit">Criar iniciativa</button></div>
        </form>
    </div>
</x-app-layout>
