<x-app-layout>
<x-slot name="header"><div><h1 class="text-xl font-bold text-[#24313A]">Baselines do projeto</h1><p class="mt-1 text-sm text-[#667680]">{{ $project->code }} · {{ $project->name }}</p></div></x-slot>
<div class="mx-auto max-w-7xl space-y-6">
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section class="sgp-page-intro"><p class="sgp-page-kicker">Configuração controlada</p><h2 class="mt-2 text-2xl font-bold">Um ponto de referência verificável</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-white/80">Cada versão preserva a composição escolhida naquele momento. Os registros continuam evoluindo normalmente e uma nova baseline é criada quando necessário.</p></section>
<div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.7fr)]">
<section class="sgp-card p-6"><h2 class="sgp-section-heading">Histórico</h2><div class="mt-5 space-y-3">@forelse($project->baselines as $baseline)<a href="{{ route('projects.baselines.show',[$project,$baseline]) }}" class="flex items-center justify-between rounded-xl border border-[#DCE3E7] p-4 hover:bg-[#F8FAFB]"><div><p class="font-bold text-[#24313A]">BL {{ $baseline->version }} · {{ $baseline->title }}</p><p class="mt-1 text-xs text-[#667680]">{{ $baseline->established_at->format('d/m/Y H:i') }} · {{ $baseline->creator->name }} · {{ $baseline->items->count() }} itens</p></div><span class="text-[#287EA1]">→</span></a>@empty<div class="sgp-empty-state"><h3 class="font-bold">Nenhuma baseline constituída</h3><p class="mt-2 text-sm text-[#667680]">O projeto segue normalmente até que uma referência formal seja necessária.</p></div>@endforelse</div></section>
@if($canManage)<form method="POST" action="{{ route('projects.baselines.store',$project) }}" class="sgp-card p-6">@csrf<h2 class="sgp-section-heading">Constituir nova baseline</h2><p class="sgp-section-description">A composição será imutável após a confirmação.</p>
<div class="mt-5 space-y-4"><div><label class="sgp-field-label">Título *</label><input class="sgp-input" name="title" required value="{{ old('title','Referência de gestão') }}"></div><div><label class="sgp-field-label">Justificativa *</label><textarea class="sgp-input" name="justification" rows="3" required>{{ old('justification') }}</textarea></div>
@foreach([['requirements','Requisitos ativos',$project->requirements],['artifacts','Documentos estruturados',$project->artifacts],['contracts','Contratos',$project->contracts],['origin_documents','Documentos de origem vigentes',$project->originDocumentVersions]] as [$name,$label,$items])<fieldset class="rounded-xl border border-[#DCE3E7] p-4"><legend class="px-2 text-sm font-bold text-[#24313A]">{{ $label }}</legend><div class="mt-2 max-h-44 space-y-2 overflow-auto">@forelse($items as $item)<label class="flex gap-2 text-sm"><input type="checkbox" name="{{ $name }}[]" value="{{ $item->id }}" class="mt-1 rounded text-[#123B4A]" @checked(in_array($item->id,old($name,[])))><span>{{ $item->code ?? $item->origin_title ?? $item->original_name }} · {{ $item->title ?? $item->origin_title ?? $item->original_name }}</span></label>@empty<p class="text-xs text-[#667680]">Nenhum item disponível.</p>@endforelse</div></fieldset>@endforeach
<button class="sgp-button-primary" onclick="return confirm('Constituir esta baseline? A versão não poderá ser editada ou excluída.')">Constituir baseline</button></div></form>@endif
</div><a class="sgp-button-secondary inline-flex sm:w-auto" href="{{ route('projects.show',$project) }}">Voltar ao projeto</a></div>
</x-app-layout>
