<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
Schema::create('opportunities',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('initiative_id');$t->string('code');$t->string('title');$t->text('summary')->nullable();$t->string('state')->default('open');$t->string('priority')->default('normal');$t->decimal('estimated_value',14,2)->nullable();$t->date('expected_decision_at')->nullable();$t->foreignId('commercial_owner_id')->nullable()->constrained('users')->nullOnDelete();$t->text('loss_reason')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamp('archived_at')->nullable();$t->timestamps();$t->unique(['initiative_id','organization_id']);$t->unique(['id','organization_id']);$t->foreign(['initiative_id','organization_id'])->references(['id','organization_id'])->on('initiatives')->restrictOnDelete();});
Schema::create('initial_assessments',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('opportunity_id');$t->string('state')->default('draft');foreach(['needs','constraints','assumptions','objectives','participants','observations']as$c)$t->text($c)->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->foreign(['opportunity_id','organization_id'])->references(['id','organization_id'])->on('opportunities')->restrictOnDelete();});
Schema::create('proposals',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('initiative_id');$t->unsignedBigInteger('opportunity_id');$t->string('code');$t->string('state')->default('draft');$t->unsignedInteger('current_sequence')->default(1);$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['id','organization_id']);$t->foreign(['initiative_id','organization_id'])->references(['id','organization_id'])->on('initiatives')->restrictOnDelete();$t->foreign(['opportunity_id','organization_id'])->references(['id','organization_id'])->on('opportunities')->restrictOnDelete();});
Schema::create('proposal_versions',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('proposal_id');$t->unsignedInteger('sequence');foreach(['scope_summary','solution_summary','assumptions','exclusions','payment_terms','change_reason']as$c)$t->text($c)->nullable();$t->date('estimated_start')->nullable();$t->integer('estimated_duration')->nullable();$t->decimal('estimated_value',14,2)->nullable();$t->string('pricing_model')->nullable();$t->date('validity_until')->nullable();$t->foreignId('changed_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['proposal_id','sequence']);$t->foreign(['proposal_id','organization_id'])->references(['id','organization_id'])->on('proposals')->restrictOnDelete();});
Schema::create('negotiation_entries',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->unsignedBigInteger('initiative_id');$t->unsignedBigInteger('opportunity_id');$t->unsignedBigInteger('proposal_id')->nullable();$t->unsignedBigInteger('proposal_version_id')->nullable();$t->string('interaction_type');$t->timestamp('occurred_at');foreach(['summary','counterproposal','decision','next_step']as$c)$t->text($c)->nullable();$t->foreignId('responsible_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->foreign(['initiative_id','organization_id'])->references(['id','organization_id'])->on('initiatives')->restrictOnDelete();$t->foreign(['opportunity_id','organization_id'])->references(['id','organization_id'])->on('opportunities')->restrictOnDelete();});
Schema::create('commercial_transitions',function(Blueprint $t){$t->id();$t->unsignedBigInteger('organization_id');$t->string('subject_type');$t->unsignedBigInteger('subject_id');$t->string('from_state')->nullable();$t->string('to_state');$t->foreignId('changed_by')->constrained('users')->restrictOnDelete();$t->text('justification')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['organization_id','subject_type','subject_id']);});
}public function down():void{foreach(['commercial_transitions','negotiation_entries','proposal_versions','proposals','initial_assessments','opportunities']as$t)Schema::dropIfExists($t);}};
