<x-app-layout>
    <x-slot name="header">
        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-semibold text-[#287EA1]">{{ $task->code }}</span><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $task->status->badgeClasses() }}">{{ $task->status->label() }}</span>@unless($task->is_active)<span class="rounded-full bg-[#F3F5F6] px-3 py-1 text-xs font-semibold text-[#667680]">Inativa</span>@endunless</div><h1 class="mt-1 truncate text-xl font-bold text-[#24313A]">{{ $task->title }}</h1><p class="mt-1 text-sm text-[#667680]">{{ $project->code }} · {{ $project->name }}</p></div>
    </x-slot>
    <div class="space-y-5">
        @if(session('success'))<div class="rounded-xl border border-[#BFE2D9] bg-[#EDF8F5] px-4 py-3 text-sm font-medium text-[#256C5C]">{{ session('success') }}</div>@endif
        @include('requirements._project-nav')
        <div class="flex flex-wrap gap-3"><a href="{{ route('projects.tasks.index', $project) }}" class="inline-flex items-center rounded-lg border border-[#DCE3E7] bg-white px-4 py-2.5 text-sm font-semibold text-[#24313A] hover:bg-[#F5F7F9]">Voltar</a>@if($canManage)<a href="{{ route('projects.tasks.edit', [$project, $task]) }}" class="sgp-button-primary w-auto px-4 py-2.5">Editar tarefa</a>@if($task->is_active)<form method="POST" action="{{ route('projects.tasks.deactivate', [$project, $task]) }}" onsubmit="return confirm('Inativar esta tarefa? O histórico será preservado.')">@csrf @method('PATCH')<button class="inline-flex rounded-lg border border-[#DCE3E7] px-4 py-2.5 text-sm font-semibold text-[#667680] hover:bg-[#F5F7F9]">Inativar</button></form>@else<form method="POST" action="{{ route('projects.tasks.reactivate', [$project, $task]) }}">@csrf @method('PATCH')<button class="inline-flex rounded-lg border border-[#2E8B74] px-4 py-2.5 text-sm font-semibold text-[#2E8B74] hover:bg-[#EDF8F5]">Reativar</button></form>@endif @endif</div>

        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-[#667680]">Prioridade</p><p class="mt-3"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $task->priority->badgeClasses() }}">{{ $task->priority->label() }}</span></p></article>
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-[#667680]">Responsável</p><p class="mt-2 font-semibold text-[#24313A]">{{ $task->responsible?->name ?? 'Não definido' }}</p></article>
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-[#667680]">Prazo</p><p class="mt-2 font-semibold text-[#24313A]">{{ $task->due_date?->format('d/m/Y') ?? 'Não definido' }}</p><p class="mt-1 text-xs text-[#667680]">Início: {{ $task->start_date?->format('d/m/Y') ?? 'não informado' }}</p></article>
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-[#667680]">Estimativa</p><p class="mt-2 font-semibold text-[#24313A]">{{ $task->estimatedDuration() ?? 'Não informada' }}</p></article>
        </section>

        <section class="grid gap-5 lg:grid-cols-3">
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-6 shadow-sm lg:col-span-2"><h2 class="font-bold text-[#24313A]">Descrição</h2><p class="mt-3 whitespace-pre-line text-sm leading-6 text-[#24313A]">{{ $task->description ?: 'Sem descrição detalhada.' }}</p></article>
            <article class="rounded-2xl border border-[#DCE3E7] bg-white p-6 shadow-sm"><h2 class="font-bold text-[#24313A]">Vínculos</h2><div class="mt-4 space-y-4 text-sm"><div><p class="text-xs font-semibold uppercase text-[#667680]">Requisito</p>@if($task->requirement)<a class="mt-1 block font-semibold text-[#287EA1] hover:underline" href="{{ route('projects.requirements.show', [$project, $task->requirement]) }}">{{ $task->requirement->code }} · {{ $task->requirement->title }}</a>@else<p class="mt-1 text-[#667680]">Nenhum vínculo</p>@endif</div><div><p class="text-xs font-semibold uppercase text-[#667680]">Tarefa principal</p>@if($task->parent)<a class="mt-1 block font-semibold text-[#287EA1] hover:underline" href="{{ route('projects.tasks.show', [$project, $task->parent]) }}">{{ $task->parent->code }} · {{ $task->parent->title }}</a>@else<p class="mt-1 text-[#667680]">Não é subtarefa</p>@endif</div></div></article>
        </section>

        @if($task->subtasks->isNotEmpty())<section class="rounded-2xl border border-[#DCE3E7] bg-white p-6 shadow-sm"><h2 class="font-bold text-[#24313A]">Subtarefas</h2><div class="mt-4 divide-y divide-[#E8EDF0]">@foreach($task->subtasks as $subtask)<a href="{{ route('projects.tasks.show', [$project, $subtask]) }}" class="flex items-center justify-between gap-4 py-3 hover:bg-[#F8FAFB]"><div><p class="font-semibold text-[#1D5D73]">{{ $subtask->code }} · {{ $subtask->title }}</p><p class="mt-1 text-xs text-[#667680]">{{ $subtask->responsible?->name ?? 'Sem responsável' }}</p></div><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $subtask->status->badgeClasses() }}">{{ $subtask->status->label() }}</span></a>@endforeach</div></section>@endif

        <section class="rounded-2xl border border-[#DCE3E7] bg-white shadow-sm"><div class="border-b border-[#DCE3E7] px-6 py-5"><h2 class="font-bold text-[#24313A]">Histórico</h2><p class="mt-1 text-sm text-[#667680]">Alterações relevantes realizadas na tarefa.</p></div><div class="divide-y divide-[#E8EDF0]">@forelse($task->histories as $history)<div class="px-6 py-4 text-sm"><div class="flex flex-wrap items-center justify-between gap-2"><p class="font-semibold text-[#24313A]">{{ $history->changedBy->name }}</p><time class="text-xs text-[#667680]">{{ $history->created_at->format('d/m/Y H:i') }}</time></div><p class="mt-1 text-[#667680]">@if($history->event === 'created')Tarefa cadastrada.@elseif($history->event === 'status_changed')Status alterado de {{ \App\Enums\TaskStatus::tryFrom($history->from_status)?->label() }} para {{ \App\Enums\TaskStatus::tryFrom($history->to_status)?->label() }}.@elseif($history->event === 'deactivated')Tarefa inativada.@elseif($history->event === 'reactivated')Tarefa reativada.@else Tarefa atualizada.@endif</p>@if($history->notes)<p class="mt-2 rounded-lg bg-[#F8FAFB] px-3 py-2 text-[#667680]">{{ $history->notes }}</p>@endif</div>@empty<div class="px-6 py-8 text-center text-sm text-[#667680]">Nenhum histórico registrado.</div>@endforelse</div></section>
    </div>
</x-app-layout>
