<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-[#287EA1]">{{ $project->code }}</p><h1 class="mt-1 text-xl font-bold text-[#24313A]">Testes e homologação</h1></div></x-slot>
    <div class="space-y-5">
        @include('requirements._project-nav')
        @if(session('success'))<div class="rounded-xl border border-[#BFE2D9] bg-[#EDF8F5] px-4 py-3 text-sm font-medium text-[#256C5C]">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-xl border border-[#EABBBB] bg-[#FDF1F1] px-4 py-3 text-sm text-[#A23838]">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif

        <section class="rounded-2xl bg-gradient-to-r from-[#123B4A] to-[#287EA1] p-7 text-white shadow-sm">
            <div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-[#7FE4D0]">P08.1 · Qualidade</p><h2 class="mt-2 text-2xl font-bold">Testes verificáveis, histórico íntegro</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-100">Cada nova execução preserva a anterior. Evidências ficam vinculadas ao resultado e a decisão de homologação registra o retrato vigente.</p></div>@if($canPlan)<a href="{{ route('projects.tests.create', $project) }}" class="rounded-lg bg-white px-4 py-3 text-sm font-bold text-[#123B4A] shadow-sm">Novo caso de teste</a>@endif</div>
        </section>

        <form method="GET" class="grid gap-4 rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm sm:grid-cols-3 sm:items-end">
            <div><label class="sgp-field-label" for="status">Situação</label><select class="sgp-input" id="status" name="status"><option value="">Todas</option>@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select></div>
            <div><label class="sgp-field-label" for="severity">Severidade</label><select class="sgp-input" id="severity" name="severity"><option value="">Todas</option>@foreach($severities as $value => $label)<option value="{{ $value }}" @selected($severity === $value)>{{ $label }}</option>@endforeach</select></div>
            <button class="sgp-button-primary">Filtrar</button>
        </form>

        <section class="overflow-hidden rounded-2xl border border-[#DCE3E7] bg-white shadow-sm">
            <div class="border-b border-[#DCE3E7] px-6 py-5"><h2 class="font-bold text-[#24313A]">Casos de teste</h2></div>
            <div class="overflow-x-auto"><table class="min-w-full divide-y divide-[#E8EDF0]"><thead class="bg-[#F8FAFB]"><tr class="text-left text-xs font-semibold uppercase tracking-wider text-[#667680]"><th class="px-6 py-4">Caso</th><th class="px-6 py-4">Vínculo</th><th class="px-6 py-4">Responsável</th><th class="px-6 py-4">Último resultado</th><th class="px-6 py-4"></th></tr></thead>
                <tbody class="divide-y divide-[#E8EDF0]">@forelse($cases as $case)@php($latest = $case->latestExecution())<tr class="text-sm"><td class="px-6 py-4"><div class="flex flex-wrap gap-2"><span class="font-bold text-[#287EA1]">{{ $case->code }}</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $case->severity->badgeClasses() }}">{{ $case->severity->label() }}</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $case->status->badgeClasses() }}">{{ $case->status->label() }}</span></div><p class="mt-2 font-semibold text-[#24313A]">{{ $case->title }}</p></td><td class="px-6 py-4 text-[#667680]">{{ $case->requirement?->code ?? $case->changeRequest?->code ?? ($case->baseline ? 'Baseline v'.$case->baseline->version : 'Sem vínculo específico') }}</td><td class="px-6 py-4 text-[#24313A]">{{ $case->assignedTester?->name ?? 'Equipe de testes' }}</td><td class="px-6 py-4">@if($latest)<span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $latest->result->badgeClasses() }}">{{ $latest->result->label() }}</span><p class="mt-2 text-xs text-[#667680]">Execução {{ $latest->execution_number }} · {{ $latest->evidences->count() }} evidência(s)</p>@else<span class="text-[#667680]">Não executado</span>@endif</td><td class="px-6 py-4 text-right"><a class="font-semibold text-[#287EA1] hover:underline" href="{{ route('projects.tests.show', [$project, $case]) }}">Abrir →</a></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-sm text-[#667680]">Nenhum caso encontrado.</td></tr>@endforelse</tbody></table></div>
            @if($cases->hasPages())<div class="border-t border-[#DCE3E7] px-6 py-4">{{ $cases->links() }}</div>@endif
        </section>

        <section class="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
            <div class="overflow-hidden rounded-2xl border border-[#D8CCE8] bg-white shadow-sm"><div class="border-b border-[#E8E1F1] px-6 py-5"><h2 class="font-bold text-[#594173]">Decisões de homologação</h2><p class="mt-1 text-sm text-[#667680]">Cada decisão é imutável e preserva a contagem dos resultados naquele momento.</p></div><div class="divide-y divide-[#E8E1F1]">@forelse($homologations as $item)<article class="p-5"><div class="flex flex-wrap items-center justify-between gap-2"><div><span class="font-bold text-[#594173]">{{ $item->code }}</span><span class="ml-2 rounded-full px-2.5 py-1 text-xs font-semibold {{ $item->status->badgeClasses() }}">{{ $item->status->label() }}</span></div><span class="text-xs text-[#667680]">{{ $item->decided_at->format('d/m/Y H:i') }}</span></div><h3 class="mt-2 font-semibold text-[#24313A]">{{ $item->title }}</h3><p class="mt-1 text-sm text-[#667680]">{{ $item->decider->name }} · {{ $item->summary['passed'] ?? 0 }}/{{ $item->summary['total'] ?? 0 }} aprovados</p></article>@empty<p class="p-8 text-center text-sm text-[#667680]">Nenhuma decisão registrada.</p>@endforelse</div></div>
            @if($canHomologate)
            <form method="POST" action="{{ route('projects.homologations.store', $project) }}" class="rounded-2xl border border-[#BFE2D9] bg-[#F7FBFA] p-6 shadow-sm">@csrf<h2 class="font-bold text-[#256C5C]">Registrar decisão formal</h2><p class="mt-1 text-sm text-[#667680]">A decisão refletirá a execução mais recente de cada caso pronto.</p><div class="mt-5 space-y-4"><div><label class="sgp-field-label" for="hom_title">Título *</label><input class="sgp-input" id="hom_title" name="title" value="{{ old('title') }}" required></div><div><label class="sgp-field-label" for="hom_status">Decisão *</label><select class="sgp-input" id="hom_status" name="status" required>@foreach($homologationStatuses as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div><label class="sgp-field-label" for="hom_environment">Ambiente *</label><input class="sgp-input" id="hom_environment" name="environment" value="{{ old('environment', 'Homologação') }}" required></div><div><label class="sgp-field-label" for="hom_baseline">Baseline</label><select class="sgp-input" id="hom_baseline" name="baseline_id"><option value="">Sem baseline específica</option>@foreach($baselines as $item)<option value="{{ $item->id }}">v{{ $item->version }} · {{ $item->title }}</option>@endforeach</select></div><div><label class="sgp-field-label" for="commit_reference">Commit ou release</label><input class="sgp-input" id="commit_reference" name="commit_reference" value="{{ old('commit_reference') }}"></div><div><label class="sgp-field-label" for="hom_scope">Escopo *</label><textarea class="sgp-input min-h-24" id="hom_scope" name="scope" required>{{ old('scope') }}</textarea></div><div><label class="sgp-field-label" for="decision_notes">Fundamentação *</label><textarea class="sgp-input min-h-28" id="decision_notes" name="decision_notes" required>{{ old('decision_notes') }}</textarea></div><button class="sgp-button-primary">Registrar decisão</button></div></form>
            @else
            <div class="rounded-2xl border border-[#DCE3E7] bg-[#F8FAFB] p-6"><h2 class="font-bold text-[#24313A]">Segregação preservada</h2><p class="mt-2 text-sm leading-6 text-[#667680]">Somente participante com papel Validador pode registrar a homologação. Papéis administrativos não substituem essa responsabilidade.</p></div>
            @endif
        </section>
    </div>
</x-app-layout>
