<x-app-layout>
    <x-slot name="header"><div><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-bold text-[#287EA1]">{{ $testCase->code }}</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $testCase->severity->badgeClasses() }}">{{ $testCase->severity->label() }}</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $testCase->status->badgeClasses() }}">{{ $testCase->status->label() }}</span></div><h1 class="mt-1 text-xl font-bold text-[#24313A]">{{ $testCase->title }}</h1></div></x-slot>
    <div class="space-y-5">
        @include('requirements._project-nav')
        @if(session('success'))<div class="rounded-xl border border-[#BFE2D9] bg-[#EDF8F5] px-4 py-3 text-sm font-medium text-[#256C5C]">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-xl border border-[#EABBBB] bg-[#FDF1F1] px-4 py-3 text-sm text-[#A23838]">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
        <section class="grid gap-5 lg:grid-cols-2"><article class="rounded-2xl border border-[#DCE3E7] bg-white p-6 shadow-sm"><h2 class="font-bold text-[#24313A]">Objetivo e preparação</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="font-semibold text-[#667680]">Objetivo</dt><dd class="mt-1 whitespace-pre-line text-[#24313A]">{{ $testCase->objective }}</dd></div><div><dt class="font-semibold text-[#667680]">Precondições</dt><dd class="mt-1 whitespace-pre-line text-[#24313A]">{{ $testCase->preconditions ?: 'Não informadas.' }}</dd></div><div><dt class="font-semibold text-[#667680]">Dados</dt><dd class="mt-1 whitespace-pre-line text-[#24313A]">{{ $testCase->test_data ?: 'Não informados.' }}</dd></div></dl></article><article class="rounded-2xl border border-[#BFE2D9] bg-[#F7FBFA] p-6 shadow-sm"><h2 class="font-bold text-[#256C5C]">Procedimento verificável</h2><div class="mt-5 grid gap-5"><div><p class="text-xs font-bold uppercase tracking-wider text-[#667680]">Passos</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-[#24313A]">{{ $testCase->steps }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-[#667680]">Resultado esperado</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-[#24313A]">{{ $testCase->expected_result }}</p></div></div></article></section>
        <section class="rounded-2xl border border-[#DCE3E7] bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><p class="text-sm text-[#667680]">Responsável: <strong class="text-[#24313A]">{{ $testCase->assignedTester?->name ?? 'Equipe de testes' }}</strong> · vínculo: <strong class="text-[#24313A]">{{ $testCase->requirement?->code ?? $testCase->changeRequest?->code ?? ($testCase->baseline ? 'Baseline v'.$testCase->baseline->version : 'não informado') }}</strong></p><div class="flex gap-3"><a class="text-sm font-semibold text-[#287EA1]" href="{{ route('projects.tests.index', $project) }}">Voltar</a>@if($canPlan)<a class="text-sm font-semibold text-[#2E8B74]" href="{{ route('projects.tests.edit', [$project, $testCase]) }}">Editar caso</a>@endif</div></div></section>

        @if($canExecute)
        <form method="POST" action="{{ route('projects.tests.executions.store', [$project, $testCase]) }}" class="rounded-2xl border border-[#BFD7DF] bg-[#F4F9FA] p-6 shadow-sm">@csrf<h2 class="font-bold text-[#123B4A]">Registrar nova execução</h2><p class="mt-1 text-sm text-[#667680]">O resultado é imutável. Uma correção será registrada em nova execução.</p><div class="mt-5 grid gap-5 lg:grid-cols-2"><div><label class="sgp-field-label" for="result">Resultado *</label><select class="sgp-input" id="result" name="result" required>@foreach($results as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div><label class="sgp-field-label" for="environment">Ambiente *</label><input class="sgp-input" id="environment" name="environment" value="{{ old('environment', 'Homologação') }}" required></div><div class="lg:col-span-2"><label class="sgp-field-label" for="observed_result">Resultado observado *</label><textarea class="sgp-input min-h-28" id="observed_result" name="observed_result" required>{{ old('observed_result') }}</textarea></div><div><label class="sgp-field-label" for="defect_reference">Referência do defeito</label><input class="sgp-input" id="defect_reference" name="defect_reference" value="{{ old('defect_reference') }}"></div><div><label class="sgp-field-label" for="notes">Observações</label><textarea class="sgp-input min-h-24" id="notes" name="notes">{{ old('notes') }}</textarea></div></div><button class="sgp-button-primary mt-5 w-auto px-5">Registrar execução</button></form>
        @endif

        <section class="space-y-4"><h2 class="text-lg font-bold text-[#24313A]">Histórico de execuções</h2>@forelse($testCase->executions as $execution)<article class="rounded-2xl border border-[#DCE3E7] bg-white p-6 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><span class="font-bold text-[#24313A]">Execução {{ $execution->execution_number }}</span><span class="ml-2 rounded-full px-2.5 py-1 text-xs font-semibold {{ $execution->result->badgeClasses() }}">{{ $execution->result->label() }}</span><p class="mt-2 text-sm text-[#667680]">{{ $execution->executor->name }} · {{ $execution->executed_at->format('d/m/Y H:i') }} · {{ $execution->environment }}</p></div>@if($execution->defect_reference)<span class="rounded-full bg-[#FBE8E8] px-3 py-1 text-xs font-semibold text-[#A23838]">Defeito: {{ $execution->defect_reference }}</span>@endif</div><div class="mt-5 grid gap-4 lg:grid-cols-2"><div><p class="text-xs font-bold uppercase tracking-wider text-[#667680]">Resultado observado</p><p class="mt-2 whitespace-pre-line text-sm text-[#24313A]">{{ $execution->observed_result }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-[#667680]">Observações</p><p class="mt-2 whitespace-pre-line text-sm text-[#24313A]">{{ $execution->notes ?: 'Sem observações adicionais.' }}</p></div></div><div class="mt-5 border-t border-[#E8EDF0] pt-5"><h3 class="font-semibold text-[#24313A]">Evidências</h3><div class="mt-3 space-y-2">@forelse($execution->evidences as $evidence)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#F8FAFB] px-4 py-3 text-sm"><div><p class="font-semibold text-[#24313A]">{{ $evidence->original_name }}</p><p class="mt-1 text-xs text-[#667680]">{{ $evidence->formattedSize() }} · SHA-256 {{ substr($evidence->sha256, 0, 12) }}… · {{ $evidence->uploader->name }}</p></div><a class="font-semibold text-[#287EA1]" href="{{ route('projects.tests.evidences.download', [$project, $testCase, $execution, $evidence]) }}">Baixar</a></div>@empty<p class="text-sm text-[#667680]">Nenhuma evidência vinculada.</p>@endforelse</div>@if($canExecute)<form method="POST" enctype="multipart/form-data" action="{{ route('projects.tests.evidences.store', [$project, $testCase, $execution]) }}" class="mt-4 grid gap-3 rounded-xl border border-dashed border-[#B8C5CB] bg-[#F8FAFB] p-4 md:grid-cols-[1fr_1fr_auto] md:items-end">@csrf<div><label class="sgp-field-label">Arquivo *</label><input type="file" name="file" required class="block w-full text-sm"></div><div><label class="sgp-field-label">Descrição</label><input class="sgp-input" name="description" maxlength="500"></div><button class="sgp-button-primary md:w-auto">Vincular evidência</button></form>@endif</div></article>@empty<div class="rounded-2xl border border-dashed border-[#B8C5CB] bg-white p-10 text-center text-sm text-[#667680]">Este caso ainda não possui execução registrada.</div>@endforelse</section>
    </div>
</x-app-layout>
